/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SharedRouteImport } from './routes/_shared'
import { Route as SharedIndexRouteImport } from './routes/_shared.index'
import { Route as SharedAboutmeRouteImport } from './routes/_shared.aboutme'
import { Route as SharedSplatRouteImport } from './routes/_shared.$'

const SharedRoute = SharedRouteImport.update({
  id: '/_shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedIndexRoute = SharedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SharedRoute,
} as any)
const SharedAboutmeRoute = SharedAboutmeRouteImport.update({
  id: '/aboutme',
  path: '/aboutme',
  getParentRoute: () => SharedRoute,
} as any)
const SharedSplatRoute = SharedSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => SharedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SharedIndexRoute
  '/$': typeof SharedSplatRoute
  '/aboutme': typeof SharedAboutmeRoute
}
export interface FileRoutesByTo {
  '/$': typeof SharedSplatRoute
  '/aboutme': typeof SharedAboutmeRoute
  '/': typeof SharedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shared': typeof SharedRouteWithChildren
  '/_shared/$': typeof SharedSplatRoute
  '/_shared/aboutme': typeof SharedAboutmeRoute
  '/_shared/': typeof SharedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$' | '/aboutme'
  fileRoutesByTo: FileRoutesByTo
  to: '/$' | '/aboutme' | '/'
  id: '__root__' | '/_shared' | '/_shared/$' | '/_shared/aboutme' | '/_shared/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SharedRoute: typeof SharedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shared': {
      id: '/_shared'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shared/': {
      id: '/_shared/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SharedIndexRouteImport
      parentRoute: typeof SharedRoute
    }
    '/_shared/aboutme': {
      id: '/_shared/aboutme'
      path: '/aboutme'
      fullPath: '/aboutme'
      preLoaderRoute: typeof SharedAboutmeRouteImport
      parentRoute: typeof SharedRoute
    }
    '/_shared/$': {
      id: '/_shared/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SharedSplatRouteImport
      parentRoute: typeof SharedRoute
    }
  }
}

interface SharedRouteChildren {
  SharedSplatRoute: typeof SharedSplatRoute
  SharedAboutmeRoute: typeof SharedAboutmeRoute
  SharedIndexRoute: typeof SharedIndexRoute
}

const SharedRouteChildren: SharedRouteChildren = {
  SharedSplatRoute: SharedSplatRoute,
  SharedAboutmeRoute: SharedAboutmeRoute,
  SharedIndexRoute: SharedIndexRoute,
}

const SharedRouteWithChildren =
  SharedRoute._addFileChildren(SharedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SharedRoute: SharedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
